name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.10
        uses: actions/setup-java@v1
        with:
          java-version: "1.10"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate Javadocs
        run: mvn -B install --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Gradian
          path: staging
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ GITHUB_TOKEN }}
